[book]
authors = []
language = "en"
multilingual = false
preferred-dark-theme = "ayu"
src = "src"
site-url = "/learn/acton-by-example/"
git-repository-url = "https://github.com/actonlang/acton"
git-repository-icon = "fa-github"
edit-url-template = "https://github.com/actonlang/acton/edit/master/docs/acton-by-example/{path}"

[preprocessor.svgbob]
text_width = 8.0
text_height = 16.0
class = "bob"
font_family = "arial"
font_size = 14
stroke_width = 2.0
# there's using css-variables from theme:
stroke_color = "var(--fg)" # see default theme / variables.css
background_color = "transparent" # also useful `var(--bg)`

[output.html]
additional-css = ["svgbob.css"]

[output.html.fold]
enable = true
